version: "3"
services:
  traefik:
    image: traefik
    container_name: traefik
    command: # --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        # - ./conf/traefik.toml:/traefik.toml
    networks:
      - traefik

networks:
  traefik:
    external: true


